# ZMK build matrix for GitHub Actions
# Active keymap is determined by the cradio.keymap symlink
# (currently points to cradio-original.keymap)
---
include:
  - board: nice_nano//zmk
    shield: settings_reset
    artifact-name: settings_reset

  - board: nice_nano//zmk
    shield: cradio_left
    artifact-name: cradio_left

  - board: nice_nano//zmk
    shield: cradio_right
    artifact-name: cradio_right
