# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command and `artifact-name` to assign a name to
# distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
#     artifact-name: corne_left_with_logging
#
---
include:
  # Settings reset (always available)
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: settings_reset

  # Conservative Enhancement - minimal risk improvements
  - board: nice_nano_v2
    shield: cradio_left
    cmake-args: -DZMK_CONFIG="${GITHUB_WORKSPACE}/config/cradio-conservative.keymap"
    artifact-name: conservative_left
  - board: nice_nano_v2
    shield: cradio_right
    cmake-args: -DZMK_CONFIG="${GITHUB_WORKSPACE}/config/cradio-conservative.keymap"
    artifact-name: conservative_right
  
  # Selective HRM - RECOMMENDED starting point
  - board: nice_nano_v2
    shield: cradio_left
    cmake-args: -DZMK_CONFIG="${GITHUB_WORKSPACE}/config/cradio-selective-hrm.keymap"
    artifact-name: selective_hrm_left
  - board: nice_nano_v2
    shield: cradio_right
    cmake-args: -DZMK_CONFIG="${GITHUB_WORKSPACE}/config/cradio-selective-hrm.keymap"
    artifact-name: selective_hrm_right

  # Toggle Layers - Ben Vallack style for maximum efficiency
  - board: nice_nano_v2
    shield: cradio_left
    cmake-args: -DZMK_CONFIG="${GITHUB_WORKSPACE}/config/cradio-toggle-layers.keymap"
    artifact-name: toggle_layers_left
  - board: nice_nano_v2
    shield: cradio_right
    cmake-args: -DZMK_CONFIG="${GITHUB_WORKSPACE}/config/cradio-toggle-layers.keymap"
    artifact-name: toggle_layers_right

  # Hybrid Progressive - experimental features
  - board: nice_nano_v2
    shield: cradio_left
    cmake-args: -DZMK_CONFIG="${GITHUB_WORKSPACE}/config/cradio-hybrid.keymap"
    artifact-name: hybrid_left
  - board: nice_nano_v2
    shield: cradio_right
    cmake-args: -DZMK_CONFIG="${GITHUB_WORKSPACE}/config/cradio-hybrid.keymap"
    artifact-name: hybrid_right