layout: {qmk_keyboard: ferris_rotated}
layers:
  default:
  - [Q, W, E, R, T, Y, U, I, O, P]
  - - {t: A, h: LSHFT}
    - {t: S, h: LALT}
    - {t: D, h: LCTRL}
    - {t: F, h: LGUI}
    - G
    - H
    - {t: J, h: RGUI}
    - {t: K, h: RCTRL}
    - {t: L, h: RALT}
    - {t: '''', h: RSHFT}
  - [Z, X, C, V, B, N, M, ',', ., /]
  - - {t: TAB, h: left}
    - ENTER
    - BSPC
    - {t: SPACE, h: right}
  right:
  - ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0']
  - - '`'
    - '='
    - '-'
    - \
    - ;
    - '['
    - ']'
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  - - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  - - RSHFT
    - ESC
    - {t: ▽, type: trans}
    - {type: held}
  left:
  - [F1, F2, F3, F4, F5, F6, F7, F8, F9, F10]
  - [F11, F12, MUTE, VOL DN, VOL UP, PP, LEFT, UP, RIGHT, '']
  - ['', '', '', '', '', '', '', DOWN, DEL, '']
  - - {type: held}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  tri:
  - - '&sys_reset'
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: BT, h: '0'}
    - EP OFF
    - OUT TOG
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - '&sys_reset'
  - - '&bootloader'
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: BT, h: '1'}
    - EP ON
    - OUT BLE
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - '&bootloader'
  - - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - BT CLR
    - {t: BT, h: '2'}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - OUT USB
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  - - {type: held}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {type: held}
